In [17]:
import numpy as np

In [115]:
def swap_rows(A, a, b):
    assert (a >= 0) and (b >= 0)
    N = A.shape[0]
    assert (a < N) and (b < N)
    temp = A[a, :].copy()
    A[a, :] = A[b, :].copy()
    A[b, :] = temp

In [116]:
def BackSub1(aug_matrix,x):
    N = x.size
    [Nrow,Ncol] = aug_matrix.shape
    assert Nrow+1 == Ncol
    assert N == Nrow
    for row in range(N-1,-1,-1):
        RHS = aug_matrix[row,N]
        for coloumn in range(row+1,N):
            RHS = RHS - x[coloumn]*aug_matrix[row,coloumn]
        x[row]= RHS/aug_matrix[row,row]
    return

In [117]:
def GaussElimination(A,b):
    [Nrow,Ncol] = A.shape
    assert Nrow == Ncol
    N = Nrow
    assert b.size == N
    aug_mat = np.zeros((N,N+1))
    aug_mat[0:N,0:N] = A
    aug_mat[:,N] = b
    for coloumn in range(0,N):
        for row in range(coloumn+1,N):
            mod_row = aug_mat[row,:]
            mod_row -= (mod_row[coloumn]/aug_mat[coloumn,coloumn]*aug_mat[coloumn,:])
        aug_mat[row] = mod_row
    return aug_mat

In [181]:
"""
def max_in_row(array,s):
    # Extract the specified column
    max_num = np.max(s)
    print(max_num)
    [Nrow,Ncol] = array.shape
    print(array.shape[0])
    for i in range(0,array.shape[0]-1):
        if ((np.max(np.fabs(array[i,:]))) == max_num):
            print("Max value in row is ",i)
    return i"""

def GaussElimPivotSolve(A, b, LOUD):
    [Nrow, Ncol] = A.shape
    assert Nrow == Ncol
    N = Nrow
    aug_mat = np.zeros((N, N+1))
    aug_mat[0:N, 0:N] = A
    aug_mat[:, N] = b
    s = np.zeros(N)
    count = 0
    for row in aug_mat[:, 0:N]:
        s[count] = np.max(np.fabs(row))
        print(row)
        print(s[count])
        count += 1
    if LOUD == True:
        print("Original Augmented Matrix ", aug_mat)
    if LOUD == True:
        print("S = ", s)
    for column in range(0, N):
        #largest_pos = max_in_row(aug_mat,s) # I did it but it goes wrong,sorry
        #largest_pos = (np.argmax(np.fabs(aug_mat[column:N,column:N]/s[column]))+column)
        new_mat = aug_mat[column:N,column:N]/s[column]
        print("New_mat= ",new_mat)
        new_mat1 = np.fabs(new_mat)
        print("New_mat1 = ",new_mat1)
        max_arg = np.argmax(new_mat1)
        print(max_arg)
        z= np.max(new_mat1)
        print(z)
        """for i in new_mat1[:,0:N]:
            if (np.max(i)) == z:
                print(i)"""
        max = np.argmax(np.max(new_mat1,axis=0))
        
        print(max)
        if (max != column):
            if (LOUD == True):
                print("Swapping row ", column, " with column ", largest_pos)
                print("Pre-swap ", aug_mat)
            swap_rows(aug_mat, column, largest_pos)
            temp = s[column]
            s[column] = s[largest_pos]
            s[largest_pos] = temp
            print(s)
            if LOUD == True:
                print("\n A= ", A)
        for row in range(column + 1, N):
            mod_row = aug_mat[row, :]
            mod_row -= (mod_row[column] / aug_mat[column, column] * aug_mat[column, :])
            aug_mat[row] = mod_row

    x = np.zeros(N)
    if LOUD == True:
        print("Final augmented matrix : ", aug_mat)
    BackSub(aug_mat, x)
    return x


In [182]:
A = np.array([[3,2,1],[-1,4,5],[2,-8,10]])
ans = np.arange(3)+1.0
b = np.dot(A,ans)
print(b)
solfrmfun = GaussElimPivotSolve(A,b,LOUD = True)

[10. 22. 16.]
[3. 2. 1.]
3.0
[-1.  4.  5.]
5.0
[ 2. -8. 10.]
10.0
Original Augmented Matrix  [[ 3.  2.  1. 10.]
 [-1.  4.  5. 22.]
 [ 2. -8. 10. 16.]]
S =  [ 3.  5. 10.]
New_mat=  [[ 1.          0.66666667  0.33333333]
 [-0.33333333  1.33333333  1.66666667]
 [ 0.66666667 -2.66666667  3.33333333]]
New_mat1 =  [[1.         0.66666667 0.33333333]
 [0.33333333 1.33333333 1.66666667]
 [0.66666667 2.66666667 3.33333333]]
8
3.3333333333333335
2
Swapping row  0  with column  2
Pre-swap  [[ 3.  2.  1. 10.]
 [-1.  4.  5. 22.]
 [ 2. -8. 10. 16.]]
[10.  5.  3.]

 A=  [[ 3  2  1]
 [-1  4  5]
 [ 2 -8 10]]
New_mat=  [[ 0.   2. ]
 [ 2.8 -2.8]]
New_mat1 =  [[0.  2. ]
 [2.8 2.8]]
2
2.8
0
Swapping row  1  with column  2
Pre-swap  [[  2.  -8.  10.  16.]
 [  0.   0.  10.  30.]
 [  0.  14. -14. -14.]]
[10.  3.  5.]

 A=  [[ 3  2  1]
 [-1  4  5]
 [ 2 -8 10]]
New_mat=  [[2.]]
New_mat1 =  [[2.]]
0
2.0
0
Swapping row  2  with column  2
Pre-swap  [[  2.  -8.  10.  16.]
 [  0.  14. -14. -14.]
 [  0.   0.  10.  30

In [ ]:
# Example usage:
# Assuming you have a 2D array named 'my_array'
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Specify the column index (e.g., 1 for the second column)
column_index = 1

# Call the function
index, max_value = max_in_column(my_array, column_index)

# Print the result
print(f"The maximum value in column {column_index} is {max_value} at index {index}.")

In [ ]:
        largest_pos = (np.argmax(np.fabs(aug_mat[column:N, column:N] / s[column])) + column)
        print("Column:\n", column)
        print("Largest position:\n", largest_pos)
        print("Matrix to find the largest position iteration (Augmented_matrix):\n ", aug_mat[column:N, column:N])
        print("Matrix to find the largest position iteration (Augmented_matrix/S[iteration]):\n ",
              aug_mat[column:N, column:N] / s[column])
        print("Matrix to find the largest position iteration ((Augmented_matrix)/S[iteration])+iteration :\n",
              ((np.argmax(aug_mat[column:N, column:N] / s[column])) + column))

In [102]:
arr= np.array([[1,2,3],[4,5,100],[7,8,0]])
count = 0
s= np.zeros(3)
for row in arr[:,0:3]:
    s[count] = np.max(row)
    count+=1
print(s)
def find_max_row(array,s):
    max_num = np.max(s)
    print(max_num)
    x = 0
    for i in range(0,3):
        if np.max(array[i,:]) == max_num:
            x = i
    print(x)
            
find_max_row(arr,s)

[  3. 100.   8.]
100.0
1
